CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar,
  "name" varchar NOT NULL,
  "provider" varchar NOT NULL DEFAULT 'email',
  "provider_id" varchar,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "clientes_winet" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_user" integer NOT NULL,
  "nombre" varchar NOT NULL,
  "estado" varchar NOT NULL,
  "correo" varchar,
  "telefono" varchar,
  "movil" varchar,
  "cedula" varchar UNIQUE NOT NULL,
  "pasarela" varchar,
  "codigo" varchar UNIQUE NOT NULL,
  "direccion_principal" varchar,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "tiendas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_cliente" integer NOT NULL,
  "nombre" varchar NOT NULL,
  "direccion" varchar,
  "telefono" varchar,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "pagos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_tienda" integer NOT NULL,
  "id_cliente" integer NOT NULL,
  "monto" decimal(10,2) NOT NULL,
  "fecha_pago" timestamp NOT NULL DEFAULT (now()),
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "puntos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_cliente" integer NOT NULL,
  "puntos" integer NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "transacciones_puntos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_cliente" integer NOT NULL,
  "id_tienda" integer NOT NULL,
  "tipo" varchar NOT NULL,
  "puntos" integer NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

ALTER TABLE "tiendas" ADD FOREIGN KEY ("id_cliente") REFERENCES "clientes_winet" ("id");

ALTER TABLE "pagos" ADD FOREIGN KEY ("id_tienda") REFERENCES "tiendas" ("id");

ALTER TABLE "pagos" ADD FOREIGN KEY ("id_cliente") REFERENCES "clientes_winet" ("id");

ALTER TABLE "puntos" ADD FOREIGN KEY ("id_cliente") REFERENCES "clientes_winet" ("id");

ALTER TABLE "transacciones_puntos" ADD FOREIGN KEY ("id_cliente") REFERENCES "clientes_winet" ("id");

ALTER TABLE "transacciones_puntos" ADD FOREIGN KEY ("id_tienda") REFERENCES "tiendas" ("id");

ALTER TABLE "clientes_mikrowisp" ADD FOREIGN KEY ("id_user") REFERENCES "users" ("id");

ALTER TABLE "clientes_winet" ADD FOREIGN KEY ("id_user") REFERENCES "users" ("id");
